### ISSUE TITLE
How to solve these POMDP?

### ISSUE THREAD

**Issue by gzrjzcx** [d3sm0/gym_pomdp#1]
Hi,
Is this only environment? 
How can I solve this POMDP problem?
For example,  if I want to find the best policy for Tiger problem , do I need to implement the specific value iteration method?

**Comment by d3sm0** [comment]
Yes this only envs. If you want to find the best policy you need to implement your own method. A good starting point might be https://papers.nips.cc/paper/2010/file/edfbe1afcf9246bb0d40eb4d8027d90f-Paper.pdf
