### ISSUE TITLE
Off by 1

### ISSUE THREAD

**Issue by recurse-id** [d3sm0/gym_pomdp#2]
if the gui shows a ship of length 2, the grid will only have 1 occupied cell.  

https://github.com/d3sm0/gym_pomdp/blob/e12a521c475797f3ba7ecdf8153c07d114015de0/gym_pomdp/envs/battleship.py#L199

Can be fixed with: `for i in range(ship.length +1):`

**Comment by d3sm0** [comment]
Thanks !
